name: Caching and Artifacts
on: [workflow_dispatch]

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependancy
        run: npm ci
      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios')
            const { data } = await axios.get('https://icanhazdadjoke.com/', {
              headers: {
                Accept: 'text/plain'
              }
            })
            console.log(data)
