name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
        include:
          - os: ubuntu-latest
            is-ubuntu: true
          - os: macos-latest
            node-version: 15
          # add original combinations
          - experimental: false
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17

        exclude:
          # exclude all ubuntu-latest
          #- os: ubuntu-latest
          # exclude [os: ubuntu-latest , node-version: 14, *]
          - os: ubuntu-latest
            node-version: 14
      fail-fast: true
      # 최대 3개만 실행
      # max-parallel: 3
    runs-on: ${{ matrix.os }}
    steps:
      # matrix 의 experimental 이 true 이면
      # exit 1 실행하여 실패처리
      - if: matrix.experimental == true
        run: exit 1
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
