name: Calling Resuable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "jhoon"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: ./.github/workflows/reusable.yml
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
