name: Calling Resuable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "jhoon"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: ./.github/workflows/reusable.yml
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

  calling-a-reusable-wf-2:
    uses: ./.github/workflows/reusable-workflow.yaml

  using-reusable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf-2
    steps:
      - run: echo ${{ needs.calling-a-reusable-wf-2.outputs.date }}
