name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
jobs:
  echo-string:
    runs-on: untuntu-latest
    steps:
      - run: echo "I was triggered because 'Repository Events' was compleated"
